os: Ubuntu

environment:
  RUSTUP_USE_HYPER: 1
  CARGO_HTTP_CHECK_REVOKE: false

  matrix:
  - CRATE_DIR: bip_bencode

  - CRATE_DIR: bip_dht

  - CRATE_DIR: bip_disk

  - CRATE_DIR: bip_handshake

  - CRATE_DIR: bip_htracker

  - CRATE_DIR: bip_lpd

  - CRATE_DIR: bip_magnet

  - CRATE_DIR: bip_metainfo

  - CRATE_DIR: bip_peer

  - CRATE_DIR: bip_util

  - CRATE_DIR: bip_utracker

install:
  - curl https://sh.rustup.rs -sSf | sh
  - source $HOME/.cargo/env
  - rustc --version
  - cargo --version

build: false

test_script:
  - cd $CRATE_DIR
  - cargo build
  - cargo test --verbose